CREATE SCHEMA IF NOT EXISTS test;
USE test;

DROP TABLE IF EXISTS students;
CREATE TABLE students(id SERIAL PRIMARY KEY, name VARCHAR(80), surname VARCHAR(80));
CREATE TABLE subjects(id SERIAL PRIMARY KEY, student_id BIGINT, name VARCHAR(80));